/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Beans.LeilaoBeans;
import DAO.LeilaoDAO;
import javax.swing.JFrame;

/**
 *
 * @author Eu
 */
public class Fipe extends javax.swing.JFrame {

    LeilaoDAO leilaoD;

    public Fipe() {
        initComponents();
        leilaoD = new LeilaoDAO();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        cmb_leilao.addItem("Selecionar Leilao");
        for (LeilaoBeans leilao : leilaoD.buscarTodosLeiloes()) {
            cmb_leilao.addItem(leilao);
        }
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmb_leilao = new javax.swing.JComboBox<>();
        btn_busca = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txt_totalDoc = new javax.swing.JTextField();
        txt_totalFVU = new javax.swing.JTextField();
        txt_Totalsucata = new javax.swing.JTextField();
        txt_totalGeral = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_desvDoc = new javax.swing.JTextField();
        txt_desvFVU = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_desvSucata = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btn_fipe = new javax.swing.JButton();
        btn_debito = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Leilão");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        getContentPane().add(cmb_leilao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 240, -1));

        btn_busca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Search.png"))); // NOI18N
        getContentPane().add(btn_busca, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 22, 39, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Excel_32.png"))); // NOI18N
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 22, 39, 29));

        txt_totalDoc.setEditable(false);
        getContentPane().add(txt_totalDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 31, 114, -1));

        txt_totalFVU.setEditable(false);
        getContentPane().add(txt_totalFVU, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 31, 114, -1));

        txt_Totalsucata.setEditable(false);
        getContentPane().add(txt_Totalsucata, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 31, 114, -1));

        txt_totalGeral.setEditable(false);
        getContentPane().add(txt_totalGeral, new org.netbeans.lib.awtextra.AbsoluteConstraints(847, 31, 125, -1));

        jLabel2.setText("Total Com Doc.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 11, -1, -1));

        jLabel3.setText("Total F.V.Util");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 11, -1, -1));

        jLabel4.setText("Total Sucata");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 11, -1, -1));

        jLabel5.setText("Total Geral");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(847, 11, -1, -1));

        jLabel6.setText("Desv. Com Doc");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 57, 114, -1));

        txt_desvDoc.setEditable(false);
        getContentPane().add(txt_desvDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 77, 114, -1));

        txt_desvFVU.setEditable(false);
        getContentPane().add(txt_desvFVU, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 77, 114, -1));

        jLabel7.setText("Desv. F.V.Util");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 57, -1, -1));

        jLabel8.setText("Desv. Sucata");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 57, 110, -1));

        txt_desvSucata.setEditable(false);
        getContentPane().add(txt_desvSucata, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 77, 114, -1));

        jLabel9.setText("Valor Fipe");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, -1, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, 80, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 82, 80, -1));

        jLabel10.setText("Valor Débito");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 62, -1, -1));
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 82, 39, 0));

        btn_fipe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/money.png"))); // NOI18N
        getContentPane().add(btn_fipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 67, 39, 35));

        btn_debito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/money.png"))); // NOI18N
        getContentPane().add(btn_debito, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 67, 39, 35));

        jLabel11.setText("jLabel11");

        jLabel12.setText("jLabel11");

        jLabel14.setText("jLabel11");

        jLabel16.setText("jLabel11");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 108, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lote", "Placa", "Marca", "Modelo", "Fipe", "Débito", "Com Doc", "Sem Doc", "Classificação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(100);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 391, 1140, 307));

        jLabel13.setText("Total");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 709, -1, -1));

        setBounds(0, 0, 1176, 762);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fipe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_busca;
    private javax.swing.JButton btn_debito;
    private javax.swing.JButton btn_fipe;
    private javax.swing.JComboBox<Object> cmb_leilao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField txt_Totalsucata;
    private javax.swing.JTextField txt_desvDoc;
    private javax.swing.JTextField txt_desvFVU;
    private javax.swing.JTextField txt_desvSucata;
    private javax.swing.JTextField txt_totalDoc;
    private javax.swing.JTextField txt_totalFVU;
    private javax.swing.JTextField txt_totalGeral;
    // End of variables declaration//GEN-END:variables
}
